name: Build and Deploy Sigdex Dev

on:
  push:
    branches:
      - '*' # Run on all branches except main
      - '!main' # Explicitly exclude main

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check devVariantName is set
        id: check-dev-variant-dev
        run: |
          DEV_VARIANT=$(grep "const devVariantName" vite.config.ts | sed "s/.*= '\(.*\)';/\1/")
          echo "devVariant is: $DEV_VARIANT"
          if [ "$DEV_VARIANT" = "" ]; then
            echo "::error::devVariantName is not set. Dev deploy cancelled."
            exit 1
          fi
          echo "dev_variant=$DEV_VARIANT" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Run test suite
        run: npx vitest run

      - name: Build site
        run: npm run build

      - name: Deploy to FTP server (dev)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.sigdex.io
          username: github@sigdex.io
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ./${{ env.dev_variant }}.sigdex.io/
          log-level: standard
